### ISSUE TITLE
Add latest scc language support

### ISSUE THREAD

**Issue by nnnnicholas** [vearutop/sccdiff#4]
I am attempting to use your GH action to count SLoC changed in a PR that contains Solidity language code, but it [does not work](https://github.com/nnnnicholas/juice-contracts/pull/2#issuecomment-1235906209).

While `scc`'s docs say it supports Solidity, I believe `sccdiff` relies on [a specific scc commit](https://github.com/vearutop/sccdiff/blob/master/go.mod#L8) that does not include the latest languages. 

Due to [an obscure `scc` bug](https://github.com/boyter/scc/issues/328), users must download and build the package themselves to get the latest supported languages, because "for whatever reason (I really need to investigate) go @latest or @master seems to get the 3.0.0 version and not what is actually sitting in master." - boyter, author of `scc`.

I would love to get this working.

**Comment by vearutop** [comment]
Ah, thank you for heads up. That should be easy to fix, give me a few minutes.

**Comment by vearutop** [comment]
Please try [`v1.0.3`](https://github.com/vearutop/sccdiff/releases/tag/v1.0.3) and let me know if it still does not work as expected.

**Comment by nnnnicholas** [comment]
It works! Thank you very much!
